# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogPari.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogPari(object):
    def setupUi(self, dialogPari):
        dialogPari.setObjectName("dialogPari")
        dialogPari.resize(400, 110)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogPari)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.spinPari = QtWidgets.QSpinBox(dialogPari)
        self.spinPari.setGeometry(QtCore.QRect(180, 40, 48, 24))
        self.spinPari.setObjectName("spinPari")
        self.b2Vies = QtWidgets.QLabel(dialogPari)
        self.b2Vies.setGeometry(QtCore.QRect(170, 10, 60, 16))
        self.b2Vies.setAlignment(QtCore.Qt.AlignCenter)
        self.b2Vies.setObjectName("b2Vies")

        self.retranslateUi(dialogPari)
        self.buttonBox.accepted.connect(dialogPari.accept)
        self.buttonBox.rejected.connect(dialogPari.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogPari)

    def retranslateUi(self, dialogPari):
        _translate = QtCore.QCoreApplication.translate
        dialogPari.setWindowTitle(_translate("dialogPari", "Votre pari"))
        self.b2Vies.setText(_translate("dialogPari", "Votre pari"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogPari = QtWidgets.QDialog()
    ui = Ui_dialogPari()
    ui.setupUi(dialogPari)
    dialogPari.show()
    sys.exit(app.exec_())
